# Generated by Django 6.0.3 on 2026-06-01 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bustype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('seat_count', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('bus_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='trips.bustype')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_datetime', models.DateField()),
                ('arrival_datetime', models.DateTimeField(blank=True, null=True)),
                ('base_price', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='trips.bus')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_trips', to='trips.city')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_trips', to='trips.city')),
            ],
            options={
                'indexes': [models.Index(fields=['origin', 'destination', 'departure_datetime'], name='trips_trip_origin__7e4434_idx')],
            },
        ),
    ]
