# Generated by Django 6.0.6 on 2026-07-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure_datetime',
            field=models.DateTimeField(),
        ),
    ]
