# Generated by Django 6.0.6 on 2026-07-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_departure_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='base_price',
            new_name='price',
        ),
    ]
