# Generated by Django 6.0.6 on 2026-07-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_rename_base_price_trip_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='available_seats',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
