# Generated by Django 6.0.6 on 2026-07-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_trip_available_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='available_seats',
            field=models.PositiveBigIntegerField(default=30),
        ),
    ]
